version: 2.1
orbs:
  datadog-agent: datadog/agent@0
  # gradle: circleci/gradle@2.2.0

jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - datadog-agent/setup
      - run: gradle test
      - datadog-agent/stop
workflows:
  spring-boot-app-workflow:
    jobs:
      # - checkout-app. 
      - test
