version: 2.1
orbs:
  datadog-agent: datadog/agent@0

jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - datadog-agent/setup
      - run: gradle test -Pdd-civisibility
      - datadog-agent/stop
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: gradle build
workflows:
  spring-boot-app-workflow:
    jobs:
      - test
      - build:
          requires:
            - test
