version: 2.1
orbs:
  datadog-agent: datadog/agent@0
  gradle: circleci/gradle@2.2.0

jobs:
  checkout-app:
    docker:
      - image: img/base:stable
    environment:
      DD_API_KEY: 61fe0e3fa0c4d4bf0bd0aea125d209cc
    steps:
      - checkout
      - datadog-agent/setup
      - run: gradle test
      - datadog-agent/stop
workflows:
  spring-boot-app-workflow:
    jobs:
      # - checkout-app
      - gradle/test
